beauty/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views


app_name = "beauty"


urlpatterns = [
    path('', views.view_index, name='start_page'),
    path('service/', views.view_service, name='service_page'),
    path('service-finally/', views.service_finally, name='service_finally')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

beauty_city/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('beauty.urls')),
]

beauty/models.py
from django.db import models
from datetime import datetime
from django.utils.translation import gettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField


class Category(models.Model):
    name = models.CharField(
        'Категория',
        max_length=25
    )

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Client(models.Model):
    fullname = models.CharField(verbose_name='Имя', max_length=255)
    phone = PhoneNumberField(
        'Номер клиента',
        blank=True,
        max_length=20,
    )

    class Meta:
        verbose_name = _('Клиент')
        verbose_name_plural = _('Клиенты')

    def __str__(self):
        return self.fullname


class Master(models.Model):
    fullname = models.CharField(verbose_name='Имя', max_length=30)

    speciality = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        default=None,
        verbose_name='Специальность',
        null=True,
        blank=True,
    )

    photo = models.ImageField(
        blank=True,
        verbose_name='Фотография'
    )

    class Meta:
        verbose_name = _('Мастер')
        verbose_name_plural = _('Мастера')

    def __str__(self):
        return self.fullname



class Salon(models.Model):
    name = models.CharField(verbose_name='Название салона', max_length=150)
    address = models.CharField(verbose_name='Адрес', max_length=255)
    photo = models.ImageField(
        blank=True,
        verbose_name='Фотография'
    )
    master = models.ManyToManyField(
        'Master',
        through='DayOfWork',
        through_fields=('salons', 'master')
    )

    class Meta:
        verbose_name = _('Салон красоты')
        verbose_name_plural = _('Салоны красоты')

    def __str__(self):
        return self.name


class Service(models.Model):
    name = models.CharField(verbose_name='Название услуги', max_length=200)
    price = models.PositiveIntegerField(verbose_name='Цена услуги')
    photo = models.ImageField(
        blank=True,
        verbose_name='Фотография'
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        related_name='services',
        default=None,
        verbose_name='Категории',
        null = True,
        blank = True,
    )

    class Meta:
        verbose_name = _('Услуга')
        verbose_name_plural = _('Услуги')

    def __str__(self):
        return self.name


class DayOfWork(models.Model):
    MONDAY = 'Mo'
    TUESDAY = 'Tu'
    WEDNESDAY = 'We'
    THURSDAY = 'Td'
    FRIDAY = 'Fr'
    SATURDAY = 'Sa'
    SUNDAY = 'Su'

    DAYS_OF_WEEK = [
        (MONDAY, 'Пн'),
        (TUESDAY, 'Вт'),
        (WEDNESDAY, 'Ср'),
        (THURSDAY, 'Чт'),
        (FRIDAY, 'Пт'),
        (SATURDAY, 'Сб'),
        (SUNDAY, 'Вс')
    ]

    day_of_week = models.CharField(
        max_length=20,
        verbose_name='Рабочие дни',
        choices=DAYS_OF_WEEK,
        blank=True
    )

    ready = models.BooleanField(
        default=False
    )

    master = models.ForeignKey(
        Master,
        on_delete=models.CASCADE,
        related_name='day_of_works',
        verbose_name='Мастер'
    )

    salons = models.ForeignKey(
        Salon,
        on_delete=models.CASCADE,
        related_name='day_of_works'
    )


class Order(models.Model):
    MORNING_1 = '9:00'
    MORNING_2 = '10:00'
    MORNING_3 = '11:00'
    AFTERNOON_1 = '12:00'
    AFTERNOON_2 = '13:00'
    AFTERNOON_3 = '14:00'
    DAY_1 = '15:00'
    DAY_2 = '16:00'
    DAY_3 = '17:00'
    EVENING_1 = '18:00'
    EVENING_2 = '19:00'
    EVENING_3 = '20:00'
    day_times = {
        MORNING_1, MORNING_2, MORNING_2, MORNING_3, AFTERNOON_1, AFTERNOON_2,
        AFTERNOON_3, DAY_1, DAY_2, DAY_3, EVENING_1, EVENING_2, EVENING_3
    }
    WORK_HOURS = [
        (MORNING_1, MORNING_1),
        (MORNING_2, MORNING_2),
        (MORNING_3, MORNING_3),
        (AFTERNOON_1, AFTERNOON_1),
        (AFTERNOON_2, AFTERNOON_2),
        (AFTERNOON_3, AFTERNOON_3),
        (DAY_1, DAY_1),
        (DAY_2, DAY_2),
        (DAY_3, DAY_3),
        (EVENING_1, EVENING_1),
        (EVENING_2, EVENING_2),
        (EVENING_3, EVENING_3),
    ]

    client = models.ForeignKey(
        Client,
        on_delete=models.CASCADE,
        verbose_name='Клиент'
    )

    salon = models.ForeignKey(
        Salon,
        on_delete=models.CASCADE,
        verbose_name='Салон'
    )
    service = models.ForeignKey(
        Service,
        on_delete=models.CASCADE,
        verbose_name='Услуги'
    )
    master = models.ForeignKey(
        Master,
        on_delete=models.CASCADE,
        verbose_name='Мастер'
    )
    appointment_hour = models.CharField(
        max_length=15,
        verbose_name='Время записи',
        choices=WORK_HOURS,
        blank=True
    )
    client_name = models.CharField('имя клиента', max_length=100, null=True, blank=True)
    date = models.DateField(
        'Дата',
        null=True
    )

    class Meta:
        verbose_name = _('Заказ')
        verbose_name_plural = _('Заказы')

    def __str__(self):
        return str(self.id)


class Review(models.Model):
    name = models.CharField(verbose_name='Имя', max_length=30)
    master = models.ForeignKey(
        Master,
        on_delete=models.CASCADE,
        verbose_name='Mастер'
    )
    RATE_CHOICES = (
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
    )
    rate = models.PositiveSmallIntegerField(
        verbose_name="Оцените от 1 до 5",
        choices=RATE_CHOICES)
    review_text = models.TextField(verbose_name="Отзыв", max_length=500)

    class Meta:
        verbose_name = _('Отзыв')
        verbose_name_plural = _('Отзывы')

    def __str__(self):
        return f'{self.name} {self.master} {self.rate}'

beauty/views.py
from django.shortcuts import render
from beauty.models import Service, Master, Salon, Review


def view_index(request):
    services = Service.objects.all()
    salons = Salon.objects.all()
    masters = Master.objects.all()
    reviews = Review.objects.all()
    return render(
        request,
        template_name="index.html",
        context={
            'salons': salons,
            'services': services,
            'masters': masters,
            'reviews': reviews
        }
    )


def view_service(request):
    services = Service.objects.all()
    salons = Salon.objects.all()
    masters = Master.objects.all()
    return render(
        request,
        template_name="service.html",
        context={
            'salons': salons,
            'services': services,
            'masters': masters,
        }
    )


def service_finally(request):
    # Логика для отображения страницы serviceFinally.html
    return render(
        request,
        'serviceFinally.html',
    )

beauty/templates/popup.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<link rel="stylesheet" href="../static/css/main.css">
</head>
<body>
	<div class="authPopup popup">
		<div class="popup__title authPopup__title">Войти по коду</div>
		<p class="popup__text authPopup__text">Введите свой номер телефона, мы вышлем на него код</p>
		<form action="#" class="authPopup__form">
			<div class="contacts__form_inputBlock">
				<input type="text" name="tel" class="contacts__form_iunput" placeholder="+7(999)999--99-99" required="">
			</div>
			<div class="contacts__form_checkboxBlock fic">
				<input type="checkbox" class="contacts__form_checkbox" checked="">
				<span class="contacts__form_checkboxBlock__intro">Я согласен(а) с политикой конфидециоальности</span>
			</div>
			<button type="submit" class="popup__btn authPopup__btn">Отправить</button>
		</form>
	</div>

	<div class="confirmPopup popup">
		<div class="popup__title confirmPopup__title">Подтвердите номер</div>
		<p class="popup__text confirmPopup__text">Введите код, полученный по SMS на номер +7 (928) 164 48 60</p>
		<div class="confirmPopup__number">
			<input type="text" name="num1" class="tipsPopup__form_inputNum popup__input" placeholder="" required>
			<input type="text" name="num2" class="tipsPopup__form_inputNum popup__input" placeholder="" required>
			<input type="text" name="num3" class="tipsPopup__form_inputNum popup__input" placeholder="" required>
			<input type="text" name="num4" class="tipsPopup__form_inputNum popup__input" placeholder="" required>

		</div>
		<div class="confirmPopup__sms">Если SMS не пришло вы можете <a href="#" class="popup__link">запросить код повторно</a></div>
		<div class="confirmPopup__changeNumber">
			<a href="#" class="confirmPopup__link popup__link">Изменить номер телефона</a>
		</div>
	</div>

	<div class="tipsPopup popup">
		<div class="popup__title tipsPopup__title">Чаевые</div>
		<form action="#" class="tipsPopup__form">
			<div class="tipsPopup__form_intro popup__intro">Введите сумму чаевых</div>
			<input type="text" class="tipsPopup__form_input popup__input" placeholder="0.00" required>
			<button class="tipsPopup__btn popup__btn">Далее</button>
		</form>
	</div>

	<div class="paymentPopup popup">
		<div class="popup__title paymentPopup__title">Оплата</div>
		<form action="#" class="paymentPopup__form">
			<div class="paymentPopup__form_intro popup__intro">номер карты</div>
			<input type="text" name="tel" class="paymentPopup__form_input popup__input" placeholder="Введите номер" required>
			<div class="paymentPopup__form_block fic">
				<input type="text" name="mm" class="tipsPopup__form_inputMin popup__input" placeholder="ММ" required>
				<input type="text" name="gg" class="tipsPopup__form_inputMin popup__input" placeholder="ГГ" required>
			</div>
			<div class="paymentPopup__form_elems fic">
				<input type="text" name="fname" class="paymentPopup__form_inputMid popup__input" placeholder="Имя владельца" required>
				<input type="text" name="cvc" class="tipsPopup__form_inputMin popup__input" placeholder="CVC" required>
			</div>
			<div class="paymentPopup__form_intro popup__intro">Ваш e-mail(необязательно)</div>
			<input type="email" name="tel" class="paymentPopup__form_input popup__input" placeholder="pochta@mail.ru">
			<button class="tipsPopup__btn popup__btn">Оплатить</button>
		</form>
	</div>

	<div class="reviewPopup popup">
		<div class="popup__title reviewPopup__title">Отзыв</div>
		<form action="#" class="reviewPopup__form">
			<input type="text" name="fname" class="paymentPopup__form_input popup__input" placeholder="Введите имя" required>
			<div class="contacts__form_inputBlock">
				<input type="text" name="tel" class="contacts__form_iunput" placeholder="+7(999)999--99-99" required="">
			</div>
			<input type="text" name="dateVis" class="paymentPopup__form_input popup__input" placeholder="Дата посещения" required>
			<textarea name="popupTextarea" class="reviewPopup__form_textarea" placeholder="Текст отзыва"></textarea>
			<div class="contacts__form_checkboxBlock fic">
				<input type="checkbox" class="contacts__form_checkbox" checked>
				<span class="contacts__form_checkboxBlock__intro">Я согласен(а) с политикой конфидециоальности</span>
			</div>
			<button class="tipsPopup__btn popup__btn">Оплатить</button>
		</form>
	</div>
</body>
</html>

beauty/templates/service.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Beauty City</title>
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;700&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css" integrity="sha512-yHknP1/AwR+yx26cB1y0cjvQUMvEa2PFzt1c9LlS4pRQ5NOTZFWbhBig+X9G9eYW/8m0/4OXNx8pxJ6z57x0dw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css" integrity="sha512-17EgCFERpgZKcm0j0fEq1YCJuyAWdz9KUtv1EjVuaOz8pDnh/0nZxmU6BBXwaaxqoi9PQXnRWqlcDB027hgv9A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<!-- 	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css.map">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css.map"> -->
	<link rel="stylesheet" href="{% static 'css/bootstrap-grid.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/air-datepicker.css' %}">
	<script src="{% static 'js/air-datepicker.js' %}"></script>
	<link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body class="servicePage">
	<section id="mobMenu">
			<div class="mobMenu">
				<div class="container">
				<div class="mobMenu__header">
					<div class="row">
						<div class="col-4 col-md-3">
							<a href="/">
								<img src="{% static 'img/Logo.svg' %}" alt="Logo" class="logo header__logo">
							</a>
						</div>
						<div class="col-3 col-md-2">
							<img src="{% static 'img/x.svg' %}" alt="x" class="mobMenuClose">
						</div>
					</div>
				</div>
				<div class="mobMenu__content">
					<div class="row">
						<div class="col-md-3">
							<nav>
								<ul class="mobMenu__menu">
									<li class="mobMenu__menu_item">
										<a href="#" class="mobMenu__menu_link">Мастера</a>
									</li>
									<li class="mobMenu__menu_item"><a href="#" class="mobMenu__menu_link">Услуги</a></li>
									<li class="mobMenu__menu_item"><a href="#" class="mobMenu__menu_link">Отзывы</a></li>
									<li class="mobMenu__menu_item"><a href="#" class="mobMenu__menu_link">Контакты</a></li>
								</ul>
							</nav>
							<a href="#" class="mobMenu__account">Личный кабинет</a>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<button class="mobMenu__btn">Перезвоните мне</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<header id="header">
		<div class="container">
			<div class="header">
				<div class="row">
					<div class="col-2 col-md-2 mob">
						<img src="{% static 'img/hamburger.svg' %}" alt="hamburger" class="header__mobMenu">
					</div>
					<div class="col-5 col-md-3 col-lg-2">
						<a href="/">
							<img src="{% static 'img/Logo.svg' %}" alt="Logo" class="logo header__logo">
						</a>
					</div>
					<div class="col-md-5 ">
						<nav>
						<ul class="menu">
							<li class="menu__item"><a href="#" class="menu__item_link">Мастера</a></li>
							<li class="menu__item"><a href="#" class="menu__item_link">Услуги</a></li>
							<li class="menu__item"><a href="#" class="menu__item_link">Отзывы</a></li>
							<li class="menu__item"><a href="#" class="menu__item_link">Контакты</a></li>
						</ul>
					</nav>
					</div>
					<div class="col-2 col-md-2 col-lg-3">
						<div class="header__block">
						<button class="header__block_btn">Перезвоните мне</button>
						<div class="header__block_auth">
							<img src="{% static 'img/acc.svg' %}" alt="account" class="header__account_img">
							<span class="header__block_auth__intro">Войти</span>
						</div>
					</div>
					</div>
				</div>
			</div>
		</div>
	</header>
	<section id="service">
		<div class="container">
			<div class="service">
				<div class="breadCrumbs">
					<a href="{% url 'beauty:start_page' %}" class="breadCrumbs__item">На главную</a>
				</div>
				<div class="service__block">
					<h1 class="service__title">Запись на услугу</h1>
					<button class="service__btn btn">Запись по телефону</button>
				</div>
				
				<form action="#" class="service__form">
					<div class="service__form_block service__salons">
						<button class="accordion">(Выберите салон)</button>
						<div class="panel">
							{% for salon in salons %}
							<div class="accordion__block fic">
								<div class="accordion__block_intro">{{ salon.name }}</div>
								<div class="accordion__block_address">{{ salon.address }}</div>
							</div>
						  	{% endfor %}
						</div>
					</div>
                    <div class="service__form_block service__services">
                        <button class="accordion">(Выберите услугу)</button>
                        <div class="panel">
                            <button class="accordion">Парикмахерские услуги</button>
                            <div class="panel">
                                <div class="accordion__block_items">
                                    <div class="accordion__block_item fic">
                                        <div class="accordion__block_item_intro">Окрашивание волос</div>
                                        <div class="accordion__block_item_address">5 000 ₽</div>
                                    </div>
                                    <div class="accordion__block_item fic">
                                        <div class="accordion__block_item_intro">Укладка волос</div>
                                        <div class="accordion__block_item_address">1 500 ₽</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>







{#					<div class="service__form_block service__services">#}
{#						<button class="accordion">(Выберите услугу)</button>#}
{#						<div class="panel">#}
{#							{% for service in services %}#}
{#							<div class="accordion__block fic">#}
{#								<div class="accordion__block_intro">{{ service.name }}</div>#}
{#								<div class="accordion__block_address">{{ service.price }} ₽</div>#}
{#							</div>#}
{#							{% endfor %}#}
{#						</div>#}
{#					</div>#}
{#					<div class="service__form_block service__masters">#}
{#						<button class="accordion">(Выберите мастера)</button>#}
{#						<div class="panel">#}
{#							{% for master in masters %}#}
{#							<div class="accordion__block fic">#}
{#								<img src="/media/{{ master.photo }}" alt="master" class="masters__header_img">#}
{#								<div class="accordion__block_intro">{{ master.fullname }}</div>#}
{#								<div class="accordion__block_address">{{ master.speciality }}</div>#}
{#							</div>#}
{#							{% endfor %}#}
{#						</div>#}
{#					</div>#}
				</form>
			</div>
		</div>
	</section>
	<section id="time">
		<div class="container">
			<div class="time">
				<h2 class="time__title">Выберите время</h2>
				<div class="time__block">
					<div class="row">
						<div class="col-md-4">
							<div id="datepickerHere"></div>
						</div>
						<div class="col-md-8">
							<div class="time__elems">
								<div class="time__items">
									<div class="time__elems_intro">Утро</div>
									<div class="time__elems_elem fic">
										<button data-time="10:00" class="time__elems_btn">10:00</button>
										<button data-time="10:30" class="time__elems_btn">10:30</button>
									</div>
								</div>
								<div class="time__items">
									<div class="time__elems_intro">День</div>
									<div class="time__elems_elem fic">
										<button data-time="12:00" class="time__elems_btn">12:00</button>
										<button data-time="12:30" class="time__elems_btn">12:30</button>
										<button data-time="15:00" class="time__elems_btn">15:00</button>
										<button data-time="16:30" class="time__elems_btn">16:30</button>
									</div>
								</div>
								<div class="time__items">
									<div class="time__elems_intro">Вечер</div>
									<div class="time__elems_elem fic">
										<button data-time="17:00" class="time__elems_btn">17:00</button>
										<button data-time="18:30" class="time__elems_btn">18:30</button>
										<button data-time="19:00" class="time__elems_btn">19:00</button>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="time__btns">
					<div class="row">
						<div class="col-md-12">
							<button class="time__btns_next" onclick="redirectToServiceFinally()">Далее</button>
                            <button class="time__btns_home" onclick="redirectToMainPage()">На главную</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<footer id="footer">
		<div class="container">
			<div class="footer">
				<div class="footer__block">
					<div class="row">
						<div class="col-md-3 col-lg-2">
							<a href="/"><img src="{% static 'img/Logo.svg' %}" alt="logo" class="footer__logo"></a>
						</div>
						<div class="col-md-5 minMobHide">
							<nav>
								<ul class="menu">
									<li class="menu__item"><a href="#" class="menu__item_link">Мастера</a></li>
									<li class="menu__item"><a href="#" class="menu__item_link">Услуги</a></li>
									<li class="menu__item"><a href="#" class="menu__item_link">Отзывы</a></li>
									<li class="menu__item"><a href="#" class="menu__item_link">Контакты</a></li>
								</ul>
							</nav>
						</div>
					</div>
					<div class="footer__contact">
						<div class="row">
							<div class="col-md-4">
								
									<div class="footer__data">с 10:00 до 20:00  без выходных</div>
									
							</div>
							<div class="col-md-3">
								<a href="tel:+79179023800" class="contacts__info_tel">+7 (917) 902 38 00</a>
							</div>
						</div>
						<div class="row">
							<div class="col-md-5 minMobShow">
								<nav>
									<ul class="menu">
										<li class="menu__item"><a href="#" class="menu__item_link">Мастера</a></li>
										<li class="menu__item"><a href="#" class="menu__item_link">Услуги</a></li>
										<li class="menu__item"><a href="#" class="menu__item_link">Отзывы</a></li>
										<li class="menu__item"><a href="#" class="menu__item_link">Контакты</a></li>
									</ul>
								</nav>
							</div>
						</div>
					</div>
					<hr class="hr"></hr>
					<div class="footer__bottom">
						<div class="row">
							<div class="col-md-4 col-lg-3">
								<a href="#" class="footer__link">Политика конфиденциальности</a>
							</div>
							<div class="col-md-3">
								<div class="footer__copy">2022. Все права защищены</div>
							</div>
							<div class="col-md-3 col-lg-2">
								<div class="footer__social fic">
									<a href=""><img src="{% static 'img/waGray.svg' %}" alt="wa" class="contacts__social_icon"></a>
									<a href=""><img src="{% static 'img/vkGray.svg' %}" alt="vk" class="contacts__social_icon"></a>
									<a href=""><img src="{% static 'img/tgGray.svg' %}" alt="tg" class="contacts__social_icon"></a>
									<a href=""><img src="{% static 'img/instaGray.svg' %}" alt="insta" class="contacts__social_icon"></a>
								</div>
							</div>
						</div>
						
						
						
					</div>
					
				</div>
			</div>
		</div>
	</footer>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js" integrity="sha512-aVKKRRi/Q/YV+4mjoKBsE4x3H+BkegoM/em46NNlCqNTmUYADjBbeNefNxYV7giUp0VxICtqdrbqU7iVaeZNXA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js" integrity="sha512-XtmMtDEcNz2j7ekrtHvOVR4iwwaD6o/FUJe6+Zq+HgcCsk3kj4uSQQR8weQ2QVj1o0Pk6PwYLohm206ZzNfubg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
	
	<script src="{% static 'js/main.js' %}"></script>
    <script>
    function redirectToMainPage() {
        window.location.href = "{% url 'beauty:start_page' %}";
    }
    </script>
	<script>
	function redirectToServiceFinally() {
		window.location.href = "{% url 'beauty:service_finally' %}";
	}
	</script>
</body>
</html>